Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WAndCAssignment.Models;
using System.Web.Helpers;

namespace WAndCAssignment.Controllers
{
    public class CartController : Controller
    {
        static List<Product> cart = new List<Product>();
        DAO dao = new DAO();
        decimal totalPrice = 0;


        // GET: Cart
        public ActionResult Index()
        {
            List<Product> productsList = dao.AllProducts();
            return View(productsList);
        }

        public ActionResult AddItem(FormCollection form)
        {
            Product pr = new Product();
            List<Product> list = dao.AllProducts();
            bool found = false;

            if (Session["MemberName"] == null)
            {
                Console.WriteLine("Not Allowed");
            }
            else
            {
                for (int i = 0; i < list.Count && !found; i++)
                {
                    if (list[i].ProductID == form["id"].ToString())
                    {
                        pr = list[i];
                        pr.Quantity = int.Parse(form["quantity"]);
                        found = true;
                        cart.Add(list[i]);

                    }
                }
            }


            return RedirectToAction("ViewCart");
        }

        public ActionResult ViewCart()
        {
            foreach (Product p in cart)
            {
                totalPrice += p.Quantity * p.ProductPrice;
                ViewData["price"] = totalPrice;
            }
         
            return View(cart);
        }

        public ActionResult CheckOut()
        {

            if (cart.Count == 0)
            {
                return RedirectToAction("ViewCart");
            }
            else
            {
                return View("CheckOut");
            }


        }

        [HttpPost]
        public ActionResult CheckOut(FormCollection form)
        {
            string credCardNum = form["cardNumber"];
            CreditCardValidation ccv = new CreditCardValidation();
            bool validCredCard = ccv.IsValidCreditCard(credCardNum);

            if (validCredCard) 
            {
                
                DAO dao = new DAO();
                string customerEmail = TempData["CustomerEmail"].ToString();

                //Encrypted Credit card number
                string encryptedCredCard = Crypto.HashPassword(credCardNum);

                bool successfulEntry = dao.InsertCustomerCreditCard(encryptedCredCard, customerEmail) > 0;
                if (successfulEntry)
                {
                    ViewData["credCardValidation"] = "Credit Card Validated & Inserted Successfully";
                    Session.Clear();
                    Session.Abandon();
                }
                else ViewData["credCardValidation"] = "Credit Card inserted Unsuccessfully";

            } 
            else ViewData["credCardValidation"] = "Credit Card Validation Unsuccessful";



            Customers customer = new Customers();
            customer.Email = TempData["CustomerEmail"].ToString();

            foreach (Product product in cart)
            {
                totalPrice += totalPrice + product.Quantity * product.ProductPrice;

            }

            int counter1 = dao.AddOrder(Session.SessionID, DateTime.Now, customer.Email, totalPrice);
            int counter2 = 0;

            foreach (Product product in cart)
            {
                counter2 = dao.AddLineItem(product.Quantity,Session.SessionID, product.ProductID);

               
            }
            if (counter1 > 0 && counter2 > 0)
            {
                Console.Write("Perfectly Working");

            }
            else
            {
                ViewData["message"] = "Error Please Fix ASAP";
            }

            return View();
        }


        public ActionResult Delete(FormCollection form)
        {
            Product pr = new Product();
            bool found = false;

            if (Session["MemberName"] == null)
            {
                Console.WriteLine("Not Allowed");
            }
            else
            {
                for (int i = 0; i < cart.Count && !found; i++)
                {
                    if (cart[i].ProductID == form["id"].ToString())
                    {
                        pr = cart[i];
                     
                        found = true;
                        cart.Remove(cart[i]);

                    }
                }
            }
            return RedirectToAction("ViewCart");
        }


    }
    }


Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WAndCAssignment.Models;

namespace WAndCAssignment.Controllers
{
    public class ContactController : Controller
    {

        static DataSet ds;
        static DataTable dt;

        // GET: Contact
        public ActionResult Index()
        {
            if (System.IO.File.Exists(Server.MapPath(@"~/comments.xml")))
            {

                ds = new DataSet();

                ds.ReadXml(Server.MapPath(@"~/comments.xml"));

                dt = ds.Tables[0];

            }
            else
            {
                ds = new DataSet("user_comments");
                dt = new DataTable("user_comment");
                dt.Columns.Add("name");
                dt.Columns.Add("email");
                dt.Columns.Add("comments");
                ds.Tables.Add(dt);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Comments(FormCollection form, ContactModel contact)
        {
            contact = new ContactModel();

            if (ModelState.IsValid)
            {
                DataRow row = dt.NewRow();

                row["name"] = form["Name"];
                row["email"] = form["Email"];
                row["comments"] = form["Comments"];

                dt.Rows.Add(row);
                ds.WriteXml(Server.MapPath(@"~/comments.xml"));

                return View();
            }
            else return View("Index", contact);
        }

        public ActionResult ShowFeedback()
        {

            List<ContactModel> list = new List<ContactModel>();

            if (System.IO.File.Exists(Server.MapPath(@"~/comments.xml")))
            {

                DataSet ds = new DataSet();

                ds.ReadXml(Server.MapPath(@"~/comments.xml"));

                DataTable dt = ds.Tables["user_comment"];


                foreach (DataRow row in dt.Rows)
                {
                    ContactModel contact = new ContactModel();
                    contact.Name = row["name"].ToString();
                    contact.Email = row["email"].ToString();
                    contact.Comments = row["comments"].ToString();
                    list.Add(contact);
                }

            }
            return View(list);
        }




    }
}

Controllers/CustomerController.cs
using System.Web.Mvc;
using WAndCAssignment.Models;
using System.Web.Helpers;

namespace WAndCAssignment.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Register(FormCollection form, Customers member)
        {
            int count = 0;
            DAO dao = new DAO();
            member = new Customers();

            if (ModelState.IsValid)
            {
                member.FirstName = form["FirstName"];
                member.LastName = form["LastName"];
                member.Email = form["Email"];
                member.Username = form["Username"];
                member.Password = form["Password"];

                string confirmPass = form["ConfirmPassword"];
                if (member.Password != confirmPass)
                {
                    ViewData["error"] = "Password Do Not Match";
                }
                else
                {

                    count = dao.Insert(member);
                    if (count > 0)
                    {
                        ViewData["error"] = "Your Account Has Been Created Successfully You May Now Login";
                    }
                    else
                    ViewData["error"] = "Error: " + dao.message;
                }
              
            }
            return View();

        }



    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WAndCAssignment.Models;

namespace WAndCAssignment.Controllers
{
    public class ProductsController : Controller
    {
  
          public ActionResult Index()
        {

            //create a list to store values from dao class
            List<Product> list;
            DAO dao = new DAO();
            list = dao.AllProducts();

            return View(list);
        }

        public ActionResult Laptop()
        {

            List<Product> list;
            DAO dao = new DAO();
            list = dao.AllLaptop();
            return View(list);

        }

        public ActionResult Electronic()
        {

            List<Product> list;
            DAO dao = new DAO();
            list = dao.Allelectronic();
            return View(list);

        }

        public ActionResult Smartphone()
        {

            List<Product> list;
            DAO dao = new DAO();
            list = dao.AllPhones();
            return View(list);

        }


    }
}

Views/Shared/NavRegister.cshtml

@if (Session["MemberName"] != null)
{
    <li>
        @Html.ActionLink("Log out", "Logout", "Home")
    </li>

}
else
{
    <li>
        <a href='@Url.Action("Login","Home")'>
            Log In &nbsp; <span class="glyphicon glyphicon-user"></span>
        </a>
    </li>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"  content="Matteo Mart Sells, Top Quality Devices Ranging Phones, Computers 
          and other electronical components that will take users to a brand new experience, Matteo Mart Offers
          Not Only Items but also uncomparable experience to its customers" />
    <title>@ViewBag.Title - Matteo Mart - Electronic Shop </title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/font-awesome.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link rel="shortcut icon" href="~/Content/img/favicon.ico" type="image/x-png">
    <link rel="icon" href="~/Content/img/favicon.ico" type="image/x-icon">
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <a href='@Url.Action("Index", "Home")' class="navbar-brand">
                   <img src="~/Content/img/logo.png" style="height:25px; width:100px;"/>
               </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index","Home")</li>
                    <li>@Html.ActionLink("About Us","AboutUs","Home")</li>
                    @if (Session["MemberName"] == null)
                    {
                    <li>@Html.ActionLink("Sign Up", "Register", "Customer")</li>
                    }
                    <li>
                        <a href="#" class="dropdown" data-toggle="dropdown">Products <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href='@Url.Action("Index","Products")'>All Products</a></li>
                            <li><a href='@Url.Action("Laptop","Products")'>Laptops</a></li>
                            <li><a href='@Url.Action("Electronic","Products")'>Electronics</a></li>
                            <li><a href='@Url.Action("Smartphone","Products")'>Smartphones</a></li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Contact Us","Index","Contact")</li> 
                </ul>
                <div class="container">
                    <ul class="nav navbar-nav navbar-right">
                       
                        @RenderSection("Logged", false)
                        @RenderPage("NavRegister.cshtml")
                        <li> <a href='@Url.Action("ViewCart", "Cart")'>My Cart &nbsp;<span class="glyphicon glyphicon-shopping-cart"></span> </a></li>
                        <li>
                            <form style="padding-top:8px;" id="search" method="post" action='@Url.Action("SearchItem","Home")'>
                                <div class="form-inline">
                                    <input type="text" class="form-control" name="search" placeholder="Search For Items" />
                                </div>
                            </form>
                        </li>
                        <li><a id="quickSearch">Search &nbsp;<span class="glyphicon glyphicon-search"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        @RenderBody()
        </div>
        <footer class="navbar">
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                            <div class="row">
                                <div class="col-md-4">
                                    <h4>Navigation</h4>
                                    <ul class="add-padding">
                                        <li><a href='@Url.Action("Index","Home")'>Home</a></li>
                                        <li><a href='@Url.Action("AboutUs","Home")'>About</a></li>
                                        <li><a href='@Url.Action("Login","Home")'>Log in</a></li>
                                        <li><a href='@Url.Action("Index","Products")'>Our Products</a></li>
                                        <li><a href='@Url.Action("Index","Contact")'>Contact Us</a></li>
                                        <li><a href='@Url.Action("Register","Customer")'>Register Now</a></li>
                                    </ul>
                                </div>
                                <div class="col-md-4">
                                    <h4>Brand New Deals</h4>
                                    <ul class="add-padding">
                                        <li><a href="#">Iphone Watch</a></li>
                                        <li><a href="#">Google Glass</a></li>
                                        <li><a href="#">Macbook Air</a></li>
                                        <li><a href="#">Lenovo laptop</a></li>
                                    </ul>
                                </div>
                                <div class="col-md-4">
                                    <h4>Upcoming Sale Items</h4>
                                    <ul class="add-padding">
                                        <li><a href="#">Ps4</a></li>
                                        <li><a href="#">Xbox One</a></li>
                                        <li><a href="#">Samsung Phones</a></li>
                                        <li><a href="#">Gaming Laptops</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    <div class="col-md-3">
                        <br>
                        <ul class="social">
                            <li>Follow Us:</li>
                            <li><a href="https://twitter.com/?lang=en"><i class="fa fa-twitter-square fa-2x"></i></a></li>
                            <li><a href="https://www.facebook.com/matteo.sclafani?fref=ts"><i class="fa fa-facebook-official fa-2x"></i></a></li>
                            <li><a href="https://www.instagram.com/"><i class="fa fa-instagram fa-2x"></i></a></li>
                            <li><a href="https://www.instagram.com/"><i class="fa fa-pinterest fa-2x"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>

    @* ===== Scripts goes Here ====*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/MyScript.js"></script>
    @* ==== End ====  *@
</body>
</html>